name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Trigger on pushes to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your code
      - uses: actions/checkout@v3

      # 2. Set up Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Install dependencies
      - run: npm install

      # 4. Deploy with Firebase CLI
      - name: Deploy to Firebase
        run: npx firebase-tools deploy --only hosting
        env:
          FIREBASE_SERVICE_ACCOUNT_BASE64: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BASE64 }}

