name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Trigger on pushes to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your code
      - uses: actions/checkout@v3

      # 2. Set up Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Install dependencies
      - run: npm install

      # 4. Write Firebase key (from GitHub Secret) to a file
      - name: Create Firebase service account key
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > $HOME/firebase-key.json

      # 5. Deploy with Firebase CLI
      - name: Deploy to Firebase
        run: npx firebase-tools deploy --only hosting
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/firebase-key.json
